# Audio Speech Recognition Configuration

# Dataset Configuration
dataset:
  input_dir: '/home/aswath/Projects/capstone/multimodel_lipread/data/GLips_4/lipread_files'
  output_dir: '/home/aswath/Projects/capstone/multimodel_lipread/data/GLips_4/cue_data'
  num_classes: 4
  input_size: 117

# Cue Dataset Configuration
cue_dataset:
  input_dir: '/home/aswath/Projects/capstone/multimodel_lipread/data/GLips_4/cue_data'
  output_dir: '/home/aswath/Projects/capstone/multimodel_lipread/data/GLips_4/Descriptions'

# Model Configuration
model:
  name: 'resnet'  # Options: resnet, resnet_lstm, vgg, vgg_lstm, lstm_resnet, lstm_resnet_attn, lstm_resnet_trans
  version: 16
  fc_hidden_size: 512
  dropout: 0.5
  feature_dim: 512  # Output feature dimension
  
# Training Configuration
training:
  batch_size: 32
  learning_rate: 0.0005
  weight_decay: 0.0001
  epochs: 3